defmodule OctoPi.Agent.SessionEntry do
  @moduledoc """
  Typed entry union for session history.

  Every entry persisted in a SessionManager is one of these structs.
  All share three base fields:

    id        — 8-character lowercase hex, unique within a session
    parent_id — id of the predecessor entry (nil for the root)
    timestamp — ISO 8601 string (DateTime.utc_now() |> DateTime.to_iso8601())

  Port of pi-mono's SessionEntry discriminated union:
  tmp/pi-mono/packages/coding-agent/src/core/session-manager.ts lines 44-147.
  """

  alias OctoPi.Agent.SessionEntry.BranchSummaryEntry
  alias OctoPi.Agent.SessionEntry.CompactionEntry
  alias OctoPi.Agent.SessionEntry.CustomEntry
  alias OctoPi.Agent.SessionEntry.CustomMessageEntry
  alias OctoPi.Agent.SessionEntry.LabelEntry
  alias OctoPi.Agent.SessionEntry.MessageEntry
  alias OctoPi.Agent.SessionEntry.ModelChangeEntry
  alias OctoPi.Agent.SessionEntry.SessionInfoEntry

  @type t ::
          MessageEntry.t()
          | CompactionEntry.t()
          | BranchSummaryEntry.t()
          | CustomEntry.t()
          | CustomMessageEntry.t()
          | ModelChangeEntry.t()
          | LabelEntry.t()
          | SessionInfoEntry.t()

  @doc """
  Generate a collision-free 8-character lowercase hex ID.

  Retries if the candidate already exists in `existing_ids`.
  """
  @spec generate_id(MapSet.t(String.t())) :: String.t()
  def generate_id(existing_ids) do
    candidate = 4 |> :crypto.strong_rand_bytes() |> Base.encode16(case: :lower)

    if MapSet.member?(existing_ids, candidate) do
      generate_id(existing_ids)
    else
      candidate
    end
  end

  # ── Entry types ─────────────────────────────────────────────────────────────

  defmodule MessageEntry do
    @moduledoc "Wraps a User | Assistant | ToolResult message."
    @enforce_keys [:id, :parent_id, :timestamp, :message]
    @type t :: %__MODULE__{
            id: String.t(),
            parent_id: String.t() | nil,
            timestamp: String.t(),
            message: OctoPi.Agent.Message.t()
          }
    defstruct [:id, :parent_id, :timestamp, :message]
  end

  defmodule CompactionEntry do
    @moduledoc """
    Stores a context-compaction summary.

    `first_kept_entry_id` points to the oldest MessageEntry still inside
    the LLM context window after compaction — entries before it were
    replaced by `summary`.

    `from_hook?` is true when the summary was provided by an extension
    rather than generated by the built-in LLM call.
    """
    @enforce_keys [:id, :parent_id, :timestamp, :summary, :first_kept_entry_id, :tokens_before]
    @type t :: %__MODULE__{
            id: String.t(),
            parent_id: String.t() | nil,
            timestamp: String.t(),
            summary: String.t(),
            first_kept_entry_id: String.t(),
            tokens_before: non_neg_integer(),
            details: term(),
            from_hook?: boolean()
          }
    defstruct [
      :id,
      :parent_id,
      :timestamp,
      :summary,
      :first_kept_entry_id,
      :tokens_before,
      details: nil,
      from_hook?: false
    ]
  end

  defmodule BranchSummaryEntry do
    @moduledoc "Created when navigating the session tree; summarises the abandoned branch."
    @enforce_keys [:id, :parent_id, :timestamp, :from_id, :summary]
    @type t :: %__MODULE__{
            id: String.t(),
            parent_id: String.t() | nil,
            timestamp: String.t(),
            from_id: String.t(),
            summary: String.t(),
            details: term(),
            from_hook?: boolean()
          }
    defstruct [:id, :parent_id, :timestamp, :from_id, :summary, details: nil, from_hook?: false]
  end

  defmodule CustomEntry do
    @moduledoc "Extension state storage. NOT sent to the LLM."
    @enforce_keys [:id, :parent_id, :timestamp, :custom_type]
    @type t :: %__MODULE__{
            id: String.t(),
            parent_id: String.t() | nil,
            timestamp: String.t(),
            custom_type: String.t(),
            data: term()
          }
    defstruct [:id, :parent_id, :timestamp, :custom_type, data: nil]
  end

  defmodule CustomMessageEntry do
    @moduledoc """
    Extension-injected messages that DO participate in LLM context.

    `display: false` means hidden from the TUI; `display: true` means
    rendered with extension-provided styling.
    """
    @enforce_keys [:id, :parent_id, :timestamp, :custom_type, :content]
    @type content :: String.t() | [term()]
    @type t :: %__MODULE__{
            id: String.t(),
            parent_id: String.t() | nil,
            timestamp: String.t(),
            custom_type: String.t(),
            content: content(),
            display: boolean(),
            details: term()
          }
    defstruct [:id, :parent_id, :timestamp, :custom_type, :content, display: false, details: nil]
  end

  defmodule ModelChangeEntry do
    @moduledoc "Records a model switch mid-session."
    @enforce_keys [:id, :parent_id, :timestamp, :provider, :model_id]
    @type t :: %__MODULE__{
            id: String.t(),
            parent_id: String.t() | nil,
            timestamp: String.t(),
            provider: atom(),
            model_id: String.t()
          }
    defstruct [:id, :parent_id, :timestamp, :provider, :model_id]
  end

  defmodule LabelEntry do
    @moduledoc "User-defined bookmark. `label: nil` removes the label from `entry_id`."
    @enforce_keys [:id, :parent_id, :timestamp, :entry_id]
    @type t :: %__MODULE__{
            id: String.t(),
            parent_id: String.t() | nil,
            timestamp: String.t(),
            entry_id: String.t(),
            label: String.t() | nil
          }
    defstruct [:id, :parent_id, :timestamp, :entry_id, :label]
  end

  defmodule SessionInfoEntry do
    @moduledoc "Session-level metadata."
    @enforce_keys [:id, :parent_id, :timestamp, :display_name]
    @type t :: %__MODULE__{
            id: String.t(),
            parent_id: String.t() | nil,
            timestamp: String.t(),
            display_name: String.t()
          }
    defstruct [:id, :parent_id, :timestamp, :display_name]
  end
end
