defmodule OctoPi.Coder.Extensions.CustomCompaction do
  @moduledoc """
  Replaces default compaction with a full-context summary generated by an
  alternate model (Gemini Flash).

  Uses `ctx.find_model` and `ctx.get_model_auth` to resolve the alternate
  model and its credentials.  On success calls `Summary.generate/4` (D2)
  and returns `{:override, %Compaction.Result{}}`.  Falls back to `nil`
  (default compaction) when the model is unavailable, auth fails, the
  LLM call errors, or there are no messages to summarize.

  Ported from `examples/extensions/custom-compaction.ts`.
  """

  alias OctoPi.AI.Model
  alias OctoPi.Coder.Compaction.Result
  alias OctoPi.Coder.Compaction.Summary
  alias OctoPi.Coder.Extension.API

  @summarization_provider :google
  @summarization_model_id "gemini-2.5-flash"

  @spec init(API.t()) :: {:ok, API.t()}
  def init(api) do
    API.on(api, :session_before_compact, fn event, ctx -> compact(event, ctx) end)
  end

  defp compact(%{preparation: preparation}, ctx) do
    %{
      messages_to_summarize: msgs,
      turn_prefix_messages: turn_prefix,
      tokens_before: tokens_before,
      first_kept_entry_id: first_kept_entry_id,
      previous_summary: previous_summary
    } = preparation

    all_msgs = msgs ++ turn_prefix

    with [_ | _] <- all_msgs,
         %Model{} = model <- ctx.find_model.(@summarization_provider, @summarization_model_id),
         {:ok, auth} <- ctx.get_model_auth.(model),
         {:ok, summary} when summary != "" <- call_summary(all_msgs, model, previous_summary, auth, ctx) do
      {:override,
       %Result{
         summary: summary,
         first_kept_entry_id: first_kept_entry_id,
         tokens_before: tokens_before,
         details: nil
       }}
    else
      _ -> nil
    end
  end

  defp call_summary(msgs, model, previous_summary, auth, ctx) do
    base_opts = [
      api_key: Map.get(auth, :api_key),
      headers: Map.get(auth, :headers),
      previous_summary: previous_summary
    ]

    opts =
      if ctx.summary_producer,
        do: [{:producer, ctx.summary_producer} | base_opts],
        else: base_opts

    Summary.generate(msgs, model, model.max_tokens, opts)
  end
end
